INSERT INTO indicator_sources (source_id, name, category, url, description) VALUES
    ('acs-5yr',      'American Community Survey 5-Year Estimates',           'demographic',  'https://www.census.gov/programs-surveys/acs',           'Census Bureau 5-year ACS covering demographics, housing, and economic characteristics.'),
    ('cdc-places',   'CDC PLACES: Local Data for Better Health',             'health',       'https://www.cdc.gov/places',                            'CDC estimates for chronic disease measures, health outcomes, and risk behaviors at local levels.'),
    ('cdc-svi',      'CDC/ATSDR Social Vulnerability Index (SVI)',            'health',       'https://www.atsdr.cdc.gov/placeandhealth/svi/',         'CDC/ATSDR SVI ranks census tracts/counties on 16 social factors across four themes. Percentile ranks (0-1, higher=more vulnerable).'),
    ('epa-ejscreen', 'EPA EJScreen Environmental Justice Screening Tool',    'environment',  'https://www.epa.gov/ejscreen',                          'EPA environmental justice mapping tool with environmental and demographic indicators.'),
    ('hud-chas',     'HUD CHAS: Comprehensive Housing Affordability Strategy', 'housing',   'https://www.huduser.gov/portal/datasets/cp.html',       'HUD data on housing needs and affordability derived from ACS.'),
    ('usda-food',    'USDA Food Access Research Atlas',                      'food_access',  'https://www.ers.usda.gov/data-products/food-access-research-atlas/', 'USDA indicators of food access and food desert status at the census tract level.'),
    ('holc',         'HOLC Redlining Maps (Mapping Inequality)',             'historical',   'https://dsl.richmond.edu/panorama/redlining/',          'Historical Home Owners'' Loan Corporation neighborhood security grades digitized from 1930s–40s maps.'),
    ('hrsa',         'HRSA Health Resources and Services Administration',    'health',       'https://data.hrsa.gov',                                 'HRSA data on health professional shortage areas, medically underserved areas, and facility locations.'),
    ('eviction-lab', 'Princeton Eviction Lab',                               'housing',      'https://evictionlab.org',                               'Annual eviction filing and judgment rates at state, county, census tract, and city levels.'),
    ('bls-laus',     'BLS Local Area Unemployment Statistics',               'employment',   'https://www.bls.gov/lau/',                              'Bureau of Labor Statistics monthly employment, unemployment, and labor force data by area.'),
    ('gtfs',         'General Transit Feed Specification (Regional)',        'transit',      'https://gtfs.org',                                      'Standardized public transit schedule and geographic data from regional transit agencies.'),
    ('nces',         'NCES National Center for Education Statistics',        'education',    'https://nces.ed.gov',                                   'Federal education data including school locations, enrollment, demographics, and performance metrics.'),
    ('fcc-broadband', 'FCC Broadband Access Data (Form 477)',                'infrastructure', 'https://www.fcc.gov/form-477-county-data-internet-access-services', 'FCC semi-annual county-level residential fixed broadband deployment data: connections per 1,000 households and provider competition metrics.'),
    ('fbi-nibrs',     'FBI NIBRS Crime Data',                                 'crime',         'https://cde.ucr.cjis.gov/LATEST/webapp/',               'FBI National Incident-Based Reporting System (NIBRS) estimation data providing violent and property crime rates at state and county levels.')
ON CONFLICT (source_id) DO NOTHING;
